<!--Design and implementation:
        - Write a valid XML file with at least two entries with an internal DTD. Save it as ex5.xml.-->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">
]>

<NEWSPAPER>
<ARTICLE AUTHOR="Tripalovski">
<HEADLINE>VODKA</HEADLINE>
<BYLINE>OLE</BYLINE>
<BODY>A TUTI</BODY>
<NOTES>DALE JIERRO</NOTES>
</ARTICLE>

<ARTICLE AUTHOR="Jose Mari">
<HEADLINE>MORTADELA CON ACEITUNA</HEADLINE>
<BYLINE>MU WENA</BYLINE>
<BODY>PO YA VE</BODY>
<NOTES>TATE PAI</NOTES>
</ARTICLE>
</NEWSPAPER>
